// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Recap.Models;

#nullable disable

namespace Recap.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240116174518_mig")]
    partial class mig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Pjesmarrja", b =>
                {
                    b.Property<int>("PjesmarrjaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WeddingId")
                        .HasColumnType("int");

                    b.HasKey("PjesmarrjaId");

                    b.HasIndex("UserId");

                    b.HasIndex("WeddingId");

                    b.ToTable("pjesmarrjet");
                });

            modelBuilder.Entity("Recap.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Recap.Models.Wedding", b =>
                {
                    b.Property<int>("WeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WedderOne")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WedderTwo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WeddingId");

                    b.HasIndex("UserId");

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("Pjesmarrja", b =>
                {
                    b.HasOne("Recap.Models.User", "Dasmori")
                        .WithMany("dasmaKuMerrPjese")
                        .HasForeignKey("UserId");

                    b.HasOne("Recap.Models.Wedding", "Dasma")
                        .WithMany("teFtuarit")
                        .HasForeignKey("WeddingId");

                    b.Navigation("Dasma");

                    b.Navigation("Dasmori");
                });

            modelBuilder.Entity("Recap.Models.Wedding", b =>
                {
                    b.HasOne("Recap.Models.User", "Creator")
                        .WithMany("dasmatEKrijuara")
                        .HasForeignKey("UserId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Recap.Models.User", b =>
                {
                    b.Navigation("dasmaKuMerrPjese");

                    b.Navigation("dasmatEKrijuara");
                });

            modelBuilder.Entity("Recap.Models.Wedding", b =>
                {
                    b.Navigation("teFtuarit");
                });
#pragma warning restore 612, 618
        }
    }
}
